version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/jakepearson/jcpassword
    steps:
      - checkout

      - run: go get -v -t -d ./... && ./.circleci/heroku_setup.sh
      - run: go test -v ./...
      - run: git push https://git.heroku.com/jakepearson-password.git master -f
      
    
